AWSTemplateFormatVersion: 2010-09-09
Description: "WorkSpaces Stack"

Parameters:
  BundleId:
    Type: String
    Description: "The identifier of the bundle for the WorkSpace."

  DirectoryId:
    Type: String
    Description: "The identifier of the AWS Directory Service directory for the WorkSpace."

  UserName:
    Type: String
    Description: "The user name of the user for the WorkSpace."
    Default: "username"

  ComputeTypeName:
    Type: String
    Description: "The compute type of the WorkSpace."
    Default: "STANDARD"

  RootVolumeSizeGib:
    Type: Integer
    Description: "The size of the root volume."
    Default: 80

  RunningMode:
    Type: String
    Description: "The running mode of the WorkSpace."
    Default: "MANUAL"

  UserVolumeSizeGib:
    Type: Integer
    Description: "The size of the user storage."
    Default: 10

Resources:
  WindowsWorkspace:
    Type: AWS::WorkSpaces::Workspace
    Properties:
      BundleId: !Ref BundleId
      DirectoryId: !Ref DirectoryId
      UserName: !Ref UserName
      WorkspaceProperties:
        ComputeTypeName: !Ref ComputeTypeName
        RootVolumeSizeGib: !Ref RootVolumeSizeGib
        RunningMode: !Ref RunningMode
        UserVolumeSizeGib: !Ref UserVolumeSizeGib

Outputs:
  WindowsWorkspaceId:
    Description: A reference to the created WorkSpace
    Value: !Ref WindowsWorkspace
    Export:
      Name: !Sub "${AWS::StackName}-WindowsWorkspaceId"
