AWSTemplateFormatVersion: 2010-09-09

Description: "EC2 Stack"

Parameters:
  PrivateSubnetId-1a:
    Description: private subnet id
    Type: String

  PrivateSubnetId-1c:
    Description: private subnet id
    Type: String

  SecurityGroup:
    Description: security group
    Type: String

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # -------------------------------------
  # EC2 Instance (ap-northeast-1a)
  # -------------------------------------
  Instance-1a:
    Type: AWS::EC2::Instance
    Properties:
      # -------------------------------------
      # Launch Template
      # -------------------------------------
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      # -------------------------------------
      # Availability Zone
      # -------------------------------------
      AvailabilityZone: ap-northeast-1a
      # -------------------------------------
      # Network Interface
      # -------------------------------------
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: true
          DeviceIndex: "0"
          SubnetId: !Ref PrivateSubnetId-1a
          GroupSet:
            - !Ref SecurityGroup

  # -------------------------------------
  # EC2 Instance (ap-northeast-1c)
  # -------------------------------------
  Instance-1c:
    Type: AWS::EC2::Instance
    Properties:
      # -------------------------------------
      # Launch Template
      # -------------------------------------
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      # -------------------------------------
      # Availability Zone
      # -------------------------------------
      AvailabilityZone: ap-northeast-1c
      # -------------------------------------
      # Network Interface
      # -------------------------------------
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: true
          DeviceIndex: "0"
          SubnetId: !Ref PrivateSubnetId-1c
          GroupSet:
            - !Ref SecurityGroup

Outputs:
  InstanceId-1a:
    Description: "EC2 Instance ID for ap-northeast-1a"
    Value: !Ref Instance-1a

  InstanceId-1c:
    Description: "EC2 Instance ID for ap-northeast-1c"
    Value: !Ref Instance-1c
