AWSTemplateFormatVersion: 2010-09-09

Description: "EC2 Stack"

Parameters:
  PrivateSubnetId1a:
    Description: private subnet id
    Type: String

  PrivateSubnetId1c:
    Description: private subnet id
    Type: String

  SecurityGroup:
    Description: security group
    Type: String

  KeyPairName:
    Description: key pair name
    Type: String

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  TagName:
    Description: A tag name that is prefixed to resource names
    Type: String

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # -------------------------------------
  # Launch Template
  # -------------------------------------
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref EnvironmentName
      LaunchTemplateData:
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Ref TagName
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Ref TagName
          - ResourceType: network-interface
            Tags:
              - Key: Name
                Value: !Ref TagName
        BlockDeviceMappings:
          - DeviceName: /dev/sdb
            Ebs:
              VolumeType: gp3
              VolumeSize: 8
              DeleteOnTermination: true
              Encrypted: false
              Iops: 100
        EbsOptimized: false
        ImageId: ami-016415eef3351ae7d
        InstanceType: t2.medium
        CreditSpecification:
          CpuCredits: "standard"
        Monitoring:
          Enabled: False
        DisableApiTermination: true

  # -------------------------------------
  # EC2 Instance (ap-northeast-1a)
  # -------------------------------------
  Instance-1a:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      AvailabilityZone: ap-northeast-1a
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: true
          DeviceIndex: "0"
          SubnetId: !Ref PrivateSubnetId1a
          GroupSet:
            - !Ref SecurityGroup

  # -------------------------------------
  # EC2 Instance (ap-northeast-1c)
  # -------------------------------------
  Instance-1c:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      AvailabilityZone: ap-northeast-1c
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: true
          DeviceIndex: "0"
          SubnetId: !Ref PrivateSubnetId1c
          GroupSet:
            - !Ref SecurityGroup

Outputs:
  InstanceId-1a:
    Description: "EC2 Instance ID for ap-northeast-1a"
    Value: !Ref Instance-1a

  InstanceId-1c:
    Description: "EC2 Instance ID for ap-northeast-1c"
    Value: !Ref Instance-1c

  LaunchTemplateId:
    Description: "ID of the EC2 Launch Template"
    Value: !Ref EC2LaunchTemplate

  LaunchTemplateName:
    Description: "Name of the EC2 Launch Template"
    Value: !GetAtt EC2LaunchTemplate.LaunchTemplateName
